### PR TITLE
fix: require node 8 in package.json

### PR DESCRIPTION
**Pull request by BrandonOCasey**

### CODE REVIEW

**Comment by gkatsev** [comment]
fwiw, engines is basically never enforced.

**Comment by BrandonOCasey** [comment]
What about adding: https://www.npmjs.com/package/please-upgrade-node

**Comment by gkatsev** [comment]
That probably works.

**Comment by misteroneill** [comment]
Was the index.js -> generator.js change just a rename? What was the actual change, if any?

**Comment by BrandonOCasey** [comment]
The change was a rename just to make sure that the code will actually run in node < 8 since syntax like `class` won't be supported. I tested it on node 4 and 6 and it appears to exit as expected.

**Comment by misteroneill** [comment]
Sounds good, thanks.

**Pull request merged**
